username = "your username"

password = "your password"

# network operator of your wifi
# 寝室电信网: 0
# 寝室移动网: 1
# 教研室网: 2
# 教研室电信网: 3
# 默认为寝室电信网
network_operator = 0

# 后台程序检查网络状况的间隔时长
# 单位为秒，整数
# 设置为非正数时程序单独运行一次
check_interval = 1
